### ISSUE TITLE
Issue while testing $DESNEPOSE/detectron/tests/test_zero_even_op.py

### ISSUE THREAD

**Issue by sudiptabiswas22** [Johnqczhang/densepose_installation#1]
I have passed the caffe2 installation test as well as the $DENSEPOSE/detectron/tests/test_spatial_narrow_as_op.py test. However for testing $DESNEPOSE/detectron/tests/test_zero_even_op.py, I get the following error:
![Screenshot from 2019-04-02 20-20-56](https://user-images.githubusercontent.com/25134017/55412344-df2fb300-5584-11e9-858c-08e76031fac4.png)

Kindly help me resolve this issue. Thanks in advance :)

**Comment by Johnqczhang** [comment]
Close this issue since it has been solved [here](https://github.com/linkinpark213/linkinpark213.github.io/issues/12)
