### ISSUE TITLE
Missing math folder

### ISSUE THREAD

**Issue by schmidje** [Johnqczhang/densepose_installation#3]
Hi,

First of all thank you very much for this, we have been struggling a lot to install densepose in rhel 7 whose environment is like centos 7.

Most all of the procedure went smoothly (although I had to favor a caffe2 building form source instead of going through the conda binary version) except that for the step where you wrote:
"Download the source code of PyTorch, then copy the folder` $PYTORCH/caffe2/utils/threadpool` into `$TORCH_PATH/lib/include/caffe2/utils/`".

In fact, I also had to do the same but with a `math` folder:
Copy the folder` $PYTORCH/caffe2/utils/math` into `$TORCH_PATH/lib/include/caffe2/utils/`.

Don't know why, it may be related to recent updates to pytorch. You may add this mentioning that in some cases this step may be necessary.

Best regards.

**Comment by Johnqczhang** [comment]
Hi @schmidje, thanks for pointing it out. I also met this issue when I install caffe2 from source but forgot to update the installation instructions. The latest version has been updated as you suggested.
