### ISSUE TITLE
a question of make ops

### ISSUE THREAD

**Issue by zsw667291** [Johnqczhang/densepose_installation#4]
Sorry to interrupt again, I configured the environment on another computer, always follow your installation instructions, until the last "cd build && cmake .. && make" I recieved this problem:

(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 DensePose]$ cd build/
(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 build]$ cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "9.0") 
-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 9.0
-- Found CUDNN: /usr/local/cuda/include/  
-- Found cuDNN: v7.0.4  (include: /usr/local/cuda/include/, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1 6.1 6.1 6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Summary:
--   CMake version        : 3.14.0
--   CMake command        : /mnt/lustre/zhushiwei/anaconda3/envs/DensePose/bin/cmake
--   System name          : Linux
--   C++ compiler         : /bin/c++
--   C++ compiler version : 4.8.5
--   CXX flags            :  -std=c++11 -O2 -fPIC -Wno-narrowing
--   Caffe2 version       : 1.1.0
--   Caffe2 include path  : /mnt/lustre/zhushiwei/anaconda3/envs/DensePose/lib/python3.7/site-packages/torch/include
--   Caffe2 found CUDA    : True
--     CUDA version       : 9.0
--     CuDNN version      : 7.0.4
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/lustre/zhushiwei/senseTimeWork/DensePose/build
(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 build]$ make 
Scanning dependencies of target caffe2_detectron_custom_ops
[ 12%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o
[ 25%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o
[ 37%] Linking CXX shared library libcaffe2_detectron_custom_ops.so
/bin/ld: /mnt/lustre/zhushiwei/anaconda3/envs/DensePose/lib/libprotobuf.a(common.o): unrecognized relocation (0x2a) in section `.text'
/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libcaffe2_detectron_custom_ops.so] Error 1
make[1]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/all] Error 2
make: *** [all] Error 2

i tried reinstall protobuf3.6.1, but it didn't work.
look forward to your reply.

Best Wishes!

**Comment by Johnqczhang** [comment]
Hi @zsw667291, it appears to be related to your compiler. Please check this [issue](https://github.com/golang/go/issues/13678) to see if it helps. If not, make sure you've installed the correct version of gcc compiler and protobuf package.

**Comment by zsw667291** [comment]
thank u for reply.
I think I have the correct GCC version and protobuf package like this:

(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 senseTimeWork]$ strings -a /mnt/lustre/zhushiwei/anaconda3/envs/DensePose/lib/python3.7/site-packages/torch/lib/libcaffe2.so | grep "GCC: ("
GCC: (GNU) 4.9.2 20150212 (Red Hat 4.9.2-6)

 [zhushiwei@SH-IDC1-10-5-40-31 senseTimeWork]$ protoc --version
libprotoc 3.6.1

**Comment by Johnqczhang** [comment]
> thank u for reply.
> I think I have the correct GCC version and protobuf package like this:
> 
> (DensePose) [zhushiwei@SH-IDC1-10-5-40-31 senseTimeWork]$ strings -a /mnt/lustre/zhushiwei/anaconda3/envs/DensePose/lib/python3.7/site-packages/torch/lib/libcaffe2.so | grep "GCC: ("
> GCC: (GNU) 4.9.2 20150212 (Red Hat 4.9.2-6)
> 
> [zhushiwei@SH-IDC1-10-5-40-31 senseTimeWork]$ protoc --version
> libprotoc 3.6.1

How did you install caffe2? (from conda binary or source code). Can you execute the following commands to see which version of gcc you've installed,
```bash
$ which gcc
$ gcc --version
```

**Comment by zsw667291** [comment]
I install caffe2 using "conda install pytorch-nightly -c pytorch "
Because of after using the function of :

git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
git submodule sync 
git submodule update --init --recursive

when i type "from caffe2.python import core" it reply failure
It's seems like I use the wrong GCC.

$ which gcc
$ gcc --version
reply:

(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 senseTimeWork]$ which gcc
/bin/gcc
(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 senseTimeWork]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by zsw667291** [comment]
I change the gcc version(iI tried 4.9.4 and 5.3.0 ), but it not work:

(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 build]$ cmake ..
-- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
-- Check for working C compiler: /mnt/lustre/share/gcc/gcc-4.9.4/bin/gcc
-- Check for working C compiler: /mnt/lustre/share/gcc/gcc-4.9.4/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /mnt/lustre/share/gcc/gcc-4.9.4/bin/g++
-- Check for working CXX compiler: /mnt/lustre/share/gcc/gcc-4.9.4/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "9.0") 
-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 9.0
-- Found CUDNN: /usr/local/cuda/include/  
-- Found cuDNN: v7.0.4  (include: /usr/local/cuda/include/, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1 6.1 6.1 6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Summary:
--   CMake version        : 3.14.0
--   CMake command        : /mnt/lustre/zhushiwei/anaconda3/envs/DensePose/bin/cmake
--   System name          : Linux
--   C++ compiler         : /mnt/lustre/share/gcc/gcc-4.9.4/bin/g++
--   C++ compiler version : 4.9.4
--   CXX flags            :  -std=c++11 -O2 -fPIC -Wno-narrowing
--   Caffe2 version       : 1.1.0
--   Caffe2 include path  : /mnt/lustre/zhushiwei/anaconda3/envs/DensePose/lib/python3.7/site-packages/torch/include
--   Caffe2 found CUDA    : True
--     CUDA version       : 9.0
--     CuDNN version      : 7.0.4
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/lustre/zhushiwei/senseTimeWork/DensePose/build
(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 build]$ malke
-bash: malke: command not found
(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 build]$ make
Scanning dependencies of target caffe2_detectron_custom_ops
[ 12%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o
[ 25%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o
[ 37%] Linking CXX shared library libcaffe2_detectron_custom_ops.so
/bin/ld: /mnt/lustre/zhushiwei/anaconda3/envs/DensePose/lib/libprotobuf.a(common.o): unrecognized relocation (0x2a) in section `.text'
/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libcaffe2_detectron_custom_ops.so] Error 1
make[1]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/all] Error 2
make: *** [all] Error 2

-----------------------------------------------------------------------------------------------------------------------------------------

(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 build]$ cmake ..
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /mnt/lustre/share/gcc/gcc-5.3.0/bin/gcc
-- Check for working C compiler: /mnt/lustre/share/gcc/gcc-5.3.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /mnt/lustre/share/gcc/gcc-5.3.0/bin/g++
-- Check for working CXX compiler: /mnt/lustre/share/gcc/gcc-5.3.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "9.0") 
-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 9.0
-- Found CUDNN: /usr/local/cuda/include/  
-- Found cuDNN: v7.0.4  (include: /usr/local/cuda/include/, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1 6.1 6.1 6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Summary:
--   CMake version        : 3.14.0
--   CMake command        : /mnt/lustre/zhushiwei/anaconda3/envs/DensePose/bin/cmake
--   System name          : Linux
--   C++ compiler         : /mnt/lustre/share/gcc/gcc-5.3.0/bin/g++
--   C++ compiler version : 5.3.0
--   CXX flags            :  -std=c++11 -O2 -fPIC -Wno-narrowing
--   Caffe2 version       : 1.1.0
--   Caffe2 include path  : /mnt/lustre/zhushiwei/anaconda3/envs/DensePose/lib/python3.7/site-packages/torch/include
--   Caffe2 found CUDA    : True
--     CUDA version       : 9.0
--     CuDNN version      : 7.0.4
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/lustre/zhushiwei/senseTimeWork/DensePose/build
(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 build]$ make
Scanning dependencies of target caffe2_detectron_custom_ops
[ 12%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o
[ 25%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o
[ 37%] Linking CXX shared library libcaffe2_detectron_custom_ops.so
/bin/ld: /mnt/lustre/zhushiwei/anaconda3/envs/DensePose/lib/libprotobuf.a(descriptor.o): unrecognized relocation (0x29) in section `.text'
/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libcaffe2_detectron_custom_ops.so] Error 1
make[1]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/all] Error 2
make: *** [all] Error 2
(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 build]$

**Comment by Johnqczhang** [comment]
Please try gcc-4.9.2 as specified in the installation guide to see if it works.

**Comment by zsw667291** [comment]
gcc-4.9.2 is not work T-T

(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 build]$ export CXX=/mnt/lustre/zhushiwei/senseTimeWork/gcc-4.9.2/build/bin/c++
(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 build]$ export CC=/mnt/lustre/zhushiwei/senseTimeWork/gcc-4.9.2/build/bin/gcc
(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 build]$ make
make: *** No targets specified and no makefile found.  Stop.
(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 build]$ cmake ..
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /mnt/lustre/zhushiwei/senseTimeWork/gcc-4.9.2/build/bin/gcc
-- Check for working C compiler: /mnt/lustre/zhushiwei/senseTimeWork/gcc-4.9.2/build/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /mnt/lustre/zhushiwei/senseTimeWork/gcc-4.9.2/build/bin/c++
-- Check for working CXX compiler: /mnt/lustre/zhushiwei/senseTimeWork/gcc-4.9.2/build/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "9.0") 
-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 9.0
-- Found CUDNN: /usr/local/cuda/include/  
-- Found cuDNN: v7.0.4  (include: /usr/local/cuda/include/, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1 6.1 6.1 6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Summary:
--   CMake version        : 3.14.0
--   CMake command        : /mnt/lustre/zhushiwei/anaconda3/envs/DensePose/bin/cmake
--   System name          : Linux
--   C++ compiler         : /mnt/lustre/zhushiwei/senseTimeWork/gcc-4.9.2/build/bin/c++
--   C++ compiler version : 4.9.2
--   CXX flags            :  -std=c++11 -O2 -fPIC -Wno-narrowing
--   Caffe2 version       : 1.1.0
--   Caffe2 include path  : /mnt/lustre/zhushiwei/anaconda3/envs/DensePose/lib/python3.7/site-packages/torch/include
--   Caffe2 found CUDA    : True
--     CUDA version       : 9.0
--     CuDNN version      : 7.0.4
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/lustre/zhushiwei/senseTimeWork/DensePose/build
(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 build]$ make
Scanning dependencies of target caffe2_detectron_custom_ops
[ 12%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o
[ 25%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o
[ 37%] Linking CXX shared library libcaffe2_detectron_custom_ops.so
/bin/ld: /mnt/lustre/zhushiwei/anaconda3/envs/DensePose/lib/libprotobuf.a(common.o): unrecognized relocation (0x2a) in section `.text'
/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libcaffe2_detectron_custom_ops.so] Error 1
make[1]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/all] Error 2
make: *** [all] Error 2
(DensePose) [zhushiwei@SH-IDC1-10-5-40-31 build]$

**Comment by Johnqczhang** [comment]
@zsw667291 How did you install protobuf-3.6.1?

**Comment by zsw667291** [comment]
@Johnqczhang using"pip install protobuf==3.6.1"
![image](https://user-images.githubusercontent.com/28992373/57280816-2eb15380-70dc-11e9-93e7-269b4d50940c.png)

**Comment by Johnqczhang** [comment]
> @Johnqczhang using"pip install protobuf==3.6.1"
> ![image](https://user-images.githubusercontent.com/28992373/57280816-2eb15380-70dc-11e9-93e7-269b4d50940c.png)

Try uninstalling this protobuf you've installed from pip, and make sure the library files (both static and dynamic) are removed in your `$CONDA_ENV/lib/`, then reinstall it by `conda install protobuf`

**Comment by zsw667291** [comment]
![image](https://user-images.githubusercontent.com/28992373/57282232-36bec280-70df-11e9-9425-b4fa21a36bb4.png)

I am based on your opinion, install protobuf3.6.1 by conda install protobuf==3.6.1
But,it didn't work as well T-T

**Comment by Johnqczhang** [comment]
@zsw667291 Try downgrading your cmake to an old version (e.g., 3.8.2). Besides,  make sure protobuf-3.6.1 is specified in the header of `caffe2.pb.h` instead of other versions.

**Comment by Johnqczhang** [comment]
@zsw667291 You can also try this [solution](https://stackoverflow.com/questions/46058050/unable-to-compile-unrecognized-relocation).

**Comment by Johnqczhang** [comment]
This issue has been solved by upgrading `cmake` to a feasible version as specified in the installation instructions.

**Comment by ghost** [comment]
@zsw667291 It seems that the version of your binutils is too low, which makes the 'ld' command not work well with your CMakefile. Try to upgrade binutils to 2.28 or higher, this might help.

**Comment by piantou** [comment]
https://stackoverflow.com/questions/46058050/unable-to-compile-unrecognized-relocation

**Comment by poetrywanderer** [comment]
I met the same problem although with cmake 3.8.2 and gcc 4.9.2, and finally got it solved by upgrading binutils 2.24 to higher.
you can simply do it using `conda install binutils`.
