### ISSUE TITLE
Some changes I noticed while installing for pytorch-1.1.0

### ISSUE THREAD

**Issue by Ventris-L** [Johnqczhang/densepose_installation#5]
Hello.

With your help I successfully installed densepose for the first time. Thank you very much for your information. 

However, I have noticed that the installation would be easier for the latest version of pytorch binaries (installed via conda, pytorch-1.1.0 with python 3.7). The new binaries are built with protobuf 3.6.1, which can be installed through conda. Therefore it is no longer necessary to install protobuf 3.5.0 manually.

Additionally, I have noticed that some paths you provided are different from the path I figured out. I list them here just in case.
I checked the version of protobuf in `$TORCH_PATH/include/caffe2/proto` rather than `$TORCH_PATH/lib/include/caffe2/proto` . Similarly, I copied the source code directories of PyTorch to `$TORCH_PATH/include/caffe2/utils/` instead of `$TORCH_PATH/lib/include/caffe2/utils/`. (not within the 'lib' directory)

I hope this would be helpful for the new-comers. Thank you once again!

**Comment by Johnqczhang** [comment]
Hi @Ventris-L, thank you for your supporting. The instructions will be updated as you suggested.
