### ISSUE TITLE
cannot find lcaffe2_library error in pytorch 1.2

### ISSUE THREAD

**Issue by zhulinken** [Johnqczhang/densepose_installation#7]
There seems to be a problem with make ops when running on pytorch 1.2. The issue appears to be similar to [issue 238](https://github.com/facebookresearch/DensePose/issues/238) in the densepose original repository.

**Comment by Johnqczhang** [comment]
@zhulinken Maybe it's not a good idea to build densepose on PyTorch 1.2. Have you tried PyTorch 1.1.0?

**Comment by zhulinken** [comment]
I tried Pytorch 1.1.0, and it worked perfectly, thanks for your installation instruction! It save me months to fiddle around.
